# azure-pipelines.yml
# CI/CD para API de Produtos Spring Boot

trigger:
  branches:
    include:
      - main
      - hm

pr:
  branches:
    include:
      - main
      - hm

variables:
  JAVA_VERSION: '21'
  MAVEN_CACHE_FOLDER: $(Pipeline.Workspace)/.m2/repository
  MAVEN_OPTS: '-Dmaven.repo.local=$(MAVEN_CACHE_FOLDER)'
  BUILD_ARTIFACT_NAME: 'apiprodutos-artifact'

pool:
  name: Default
  demands:
    - agent.name -equals michele-token

# ========================
# STAGES
# ========================

stages:

# -------- BUILD --------
- stage: Build
  displayName: 'Build do Projeto'
  jobs:
  - job: BuildJob
    displayName: 'Compilar e Publicar Artefato'
    steps:
    - task: JavaToolInstaller@0
      inputs:
        versionSpec: $(JAVA_VERSION)
        jdkArchitectureOption: 'x64'
        jdkSourceOption: 'PreInstalled'
        preferLatestVersion: true
      displayName: 'Instalar JDK $(JAVA_VERSION)'

    - task: Maven@4
      inputs:
        mavenPomFile: 'pom.xml'
        goals: 'clean package'
        publishJUnitResults: true
        testResultsFiles: '**/surefire-reports/TEST-*.xml'
        javaHomeOption: 'JDKVersion'
        jdkVersionOption: '$(JAVA_VERSION)'
        mavenSetM2Home: true
        mavenOpts: $(MAVEN_OPTS)
      displayName: 'Compilar e Empacotar com Maven'

    - task: CopyFiles@2
      inputs:
        contents: '**/*.jar'
        targetFolder: '$(Build.ArtifactStagingDirectory)'
      displayName: 'Copiar JAR para Staging'

    - task: PublishBuildArtifacts@1
      inputs:
        pathToPublish: '$(Build.ArtifactStagingDirectory)'
        artifactName: $(BUILD_ARTIFACT_NAME)
      displayName: 'Publicar Artefato de Build'


# -------- HOMOLOGAÇÃO --------
- stage: Homologacao
  displayName: 'Deploy Homologação'
  dependsOn: Build
  condition: or(eq(variables['Build.SourceBranch'], 'refs/heads/hm'), startsWith(variables['Build.SourceBranch'], 'refs/heads/feature/'))
  jobs:
  - job: DeployHomologacao
    displayName: 'Deploy para ambiente de homologação'
    steps:
    - download: current
      artifact: $(BUILD_ARTIFACT_NAME)

    - script: |
        echo ">>> INICIANDO DEPLOY DE HOMOLOGAÇÃO"
        echo "Aqui você colocaria comandos reais para subir o .jar em seu ambiente hm"
      displayName: 'Deploy para Homologação'


# -------- PRODUÇÃO --------
- stage: Producao
  displayName: 'Deploy Produção'
  dependsOn: Build
  condition: eq(variables['Build.SourceBranch'], 'refs/heads/main')
  jobs:
  - job: DeployProducao
    displayName: 'Deploy para ambiente de produção'
    steps:
    - download: current
      artifact: $(BUILD_ARTIFACT_NAME)

    - script: |
        echo ">>> INICIANDO DEPLOY DE PRODUÇÃO"
        echo "Aqui você colocaria comandos reais para subir o .jar em seu ambiente de produção"
      displayName: 'Deploy para Produção'
